### ISSUE TITLE
Errors with configure/build in Linux Fedora

### ISSUE THREAD

**Issue by BrutPitt** [sonoro1234/anima#3]
Ciao.

I open here a new "issue", so remains in **anima** repository.

I tried to compile anima in Linux Fedora 31, configurnig CMake with this command:
`cmake -DLUAJIT_BIN=./out -DANIMA_BUILD_GLFW:BOOL=TRUE -DANIMA_BUILD_SDL:BOOL=FALSE`
and I get this errors:

### CMake configuration
```
CMake Error at LuaJIT-ImGui/CMakeLists.txt:71 (add_library):
  Cannot find source file:

    ./extras/imGuizmo/imGuizmo.cpp
```
It's CedricGuillemet's ImGuizmo, not mine... and this happens because there is a "case sensitive" mismatch in CMakeFile.txt, line 57:
`list(APPEND IMGUI_SOURCES ./extras/imGuizmo/imGuizmo.cpp ./extras/imGuizmo.cpp)` 
where, instead is `ImGuizmo.cpp`

Changing in:
`list(APPEND IMGUI_SOURCES ./extras/ImGuizmo/ImGuizmo.cpp ./extras/imGuizmo.cpp)` 
the CMake configuration is succesfull (but perhaps is need to change also appended file name ?)

### Building

**libsndfile**
```
[ 92%] Linking C shared library libsndfile.so
cc: error: folder: No such file or directory
cc: error: 5/anima/luajit-libsndfile/libsndfile/src/Symbols.gnu-binutils: No such file or directory
make[2]: *** [luajit-libsndfile/libsndfile/CMakeFiles/sndfile.dir/build.make:1404: luajit-libsndfile/libsndfile/libsndfile.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:649: luajit-libsndfile/libsndfile/CMakeFiles/sndfile.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
This happens if in path there are spaces:
in the `link.txt` file, simply editing (temporarily):
`--version-script,/home/mik27/Desktop/untitled folder 5/anima/luajit-libsndfile/libsndfile/src/Symbols.gnu-binutils`
in:
`--version-script,/home/mik27/Desktop/untitled\ folder\ 5/anima/luajit-libsndfile/libsndfile/src/Symbols.gnu-binutils`
the build continue...

**ImGuIZMO.quat**
```
In file included from /home/mik27/Desktop/untitled folder 5/anima/LuaJIT-ImGui/extras/imGuIZMO.quat/imGuIZMO.quat/imGuIZMOquat.cpp:13:
/home/mik27/Desktop/untitled folder 5/anima/LuaJIT-ImGui/extras/imGuIZMO.quat/imGuIZMO.quat/imGuIZMOquat.h:17:10: fatal error: ImGui/imgui.h: No such file or directory
   17 | #include <ImGui/imgui.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/build.make:206: LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/extras/imGuIZMO.quat/imGuIZMO.quat/imGuIZMOquat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:784: LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[mik27@Linux64 anima]$ 
```
This is a problem of how use `ImGui` folder (in general, not only in anima): is `ImGui` or `imgui` the correct one?
I guess it's `imgui`, so I need to change it!
(Eventually I can add an external define like IMGUIZMO_USE_ImGui_FOLDER to maintain olden compatibility)

**ImGuizmo** (CedricGuillemet)
```
/home/mik27/Desktop/untitled folder 5/anima/LuaJIT-ImGui/extras/imGuizmo.cpp:3:10: fatal error: imGuizmo.h: No such file or directory
    3 | #include "imGuizmo.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/build.make:245: LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/extras/imGuizmo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:784: LuaJIT-ImGui/CMakeFiles/cimgui_glfw.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I guess is linked to previous CMake configure issue

**libsimplexnoisecpp**
```
/usr/bin/ld: libsimplexnoisecpp.a(simplexnoise.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [luanoise/CMakeFiles/simplexnoise.dir/build.make:85: luanoise/simplexnoise.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:892: luanoise/CMakeFiles/simplexnoise.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Is perhaps a problem only in Fedora? (I don't know/sure)
But recompiling with **-fPIC** flag (simply adding it "on fly" in `flags.make` file) is succesful and the build is completed

**Comment by BrutPitt** [comment]
Adding...

When i run command:
` ./anima_launcher examples/shadertoy/bacteria.lua` 

I get the following error (also with other examples):
```
/home/mik27/Desktop/anima5/binary/luajit: /home/mik27/Desktop/anima5/binary/lua/imgui/glfw.lua:24: /home/mik27/Desktop/anima5/binary/libcimgui_glfw.so: undefined symbol: __glewGetUniformLocation
stack traceback:
	[C]: in function 'load'
	/home/mik27/Desktop/anima5/binary/lua/imgui/glfw.lua:24: in main chunk
	[C]: in function 'require'
	/home/mik27/Desktop/anima5/binary/lua/anima/gui.lua:1138: in function 'SetImGui'
	/home/mik27/Desktop/anima5/binary/lua/anima/canvas.lua:693: in function 'GLcanvas'
	examples/shadertoy/bacteria.lua:182: in main chunk
	[C]: at 0x00405d42
```
(missing IMGUI_IMPL_OPENGL_LOADER_GLEW define, perhaps???)

I tried the olden pre-built **x64 Linux Release**, and it works fine.

**Comment by sonoro1234** [comment]
Thanks for reporting Michele.
I have not build on linux since some months.
I will fix lower case ImGuizmo and wait until you change your include (as when doing a repo clone it is `imgui`)
Now I move to linux to keep with the tests,

**Comment by sonoro1234** [comment]
> Is perhaps a problem only in Fedora? (I don't know/sure)
> But recompiling with **-fPIC** flag (simply adding it "on fly" in `flags.make` file) is succesful and the build is completed

This did not happen in ubuntu studio. What should be done?

-fPic is not recomended for Lua modules http://lua-users.org/wiki/BuildingModules

I should detect Fedora as in
https://stackoverflow.com/questions/26919334/detect-underlying-platform-flavour-in-cmake
and use -fPic then

**Comment by sonoro1234** [comment]
> When i run command:
> ` ./anima_launcher examples/shadertoy/bacteria.lua`
> 
> I get the following error (also with other examples):

Just tested and it did not happen here. I am not using glew but gl3w so I cant understand why it happens

**Comment by sonoro1234** [comment]
> This happens if in path there are spaces:
> in the `link.txt` file, simply editing (temporarily):
> `--version-script,/home/mik27/Desktop/untitled folder 5/anima/luajit-libsndfile/libsndfile/src/Symbols.gnu-binutils`

it is in the building system of libsndfile, I will try with spaces in path an report it there.

Just tried to build with spaces in path and everything was OK!!

**Comment by BrutPitt** [comment]
The imGuIZMO.quat repo with **imgui** folder is ready.

>Is perhaps a problem only in Fedora? (I don't know/sure)
>But recompiling with -fPIC flag (simply adding it "on fly" in flags.make file) is succesful and the build is completed
> This did not happen in ubuntu studio. What should be done?

I simply followed the instruction of gcc compiler error message that suggested that I use `-fPIC`:
`.rodata' can not be used when making a shared object; recompile with -fPIC` 
https://stackoverflow.com/questions/5311515/gcc-fpic-option
(I used gcc 9.2.1)

>Just tested and it did not happen here. I am not using glew but gl3w so I cant understand why it happens

I try to find the reason...

**Comment by BrutPitt** [comment]
Adding flag -DIMGUI_IMPL_OPENGL_LOADER_GL3W to build **imgui** lib resolve my problem and the **anima** runs

Just following imgui selection loader:
```
// About Desktop OpenGL function loaders:
//  Modern desktop OpenGL doesn't have a standard portable header file to load OpenGL function pointers.
//  Helper libraries are often used for this purpose! Here we are supporting a few common ones (gl3w, glew, glad).
//  You may use another loader/header of your choice (glext, glLoadGen, etc.), or chose to manually implement your own.
#if defined(IMGUI_IMPL_OPENGL_LOADER_GL3W)
#include <GL/gl3w.h>    // Needs to be initialized with gl3wInit() in user's code
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLEW)
#include <GL/glew.h>    // Needs to be initialized with glewInit() in user's code
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD)
#include <glad/glad.h>  // Needs to be initialized with gladLoadGL() in user's code
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING)
#include <glbinding/gl/gl.h>  // Initialize with glbinding::initialize()
```

**Comment by BrutPitt** [comment]
More about **-fPIC** option...
That flag is present (autogenerated) in any `flags.make` (of any lib file, in my computer), except that in `libsimplexnoisecpp`

**Comment by sonoro1234** [comment]
It is odd that it didnt happen to me!!
I should add this define in LuaJIT-ImGui CMakeLists.txt then?

**Comment by BrutPitt** [comment]
And indeed the default one, in **ImGui** is IMGUI_IMPL_OPENGL_LOADER_GL3W ...
I'm trying to understand why from me get GL**E**W
(Moreover, never used: personally I use **glad**)

Anyway, now **anima** works great... and also imGuIZMO.quat works fine
Compliments, great work

**Comment by sonoro1234** [comment]
Great thanks for all this work!!
Just pushed fPic for linux on luanoise.
I think the only thing left is the issue with spaces in path with libsndfile, but I cant reproduce it and it is not my repo, so I dont dare to tell them to look for it

Thanks again Michele!!

**Comment by BrutPitt** [comment]
No Problem, Victor... it was a plasure.
And thanks again to insert imGuIZMO.quat between the exapmles.

P.S. I changed the title for specific reference to Fedora

**Comment by sonoro1234** [comment]
@BrutPitt 
Michele would you mind if I put in the repo qJset ported to anima as an example?

**Comment by BrutPitt** [comment]
No absolutely, Victor, quite the opposite.
Is OK for me.
